FROM w251/keras:dev-tx2-4.3_b132

RUN apt update
RUN apt install -y git
RUN pip3 install --upgrade pip
RUN apt-get install python3-opencv
ENV DEBIAN_FRONTEND=noninteractive
RUN pip3 install numpy==1.17
RUN pip3 install boto3
RUN pip3 install paho-mqtt
RUN apt install -y libcanberra-gtk-module libcanberra-gtk3-module

WORKDIR /inference/edge_network